### ISSUE TITLE
Subdomain mismatch on the url of the image

### ISSUE THREAD

**Issue by bass9030** [H2Owater425/node-hitomi#43]
## Environment
* OS: MacOS Catalina 10.15.7
* Nodejs: v16.13.2
* Npm: 8.1.2

## Code
```js
const hitomi = require('node-hitomi').default;

const gallery hitomi.getGallery(1434389).then(image => {
    const isThumb = true; // same to false
    const ext = (isThumb ? (image.hasAvif ? 'avif' : image.extension) : (((image.hasAvif) ? 'avif' : ((image.hasWebp) ? 'webp' : image.extension))));
    const url = hitomi.getImageUrl(image, ext, {isThumbnail: isThumb})
    console.log(url); // it return wrong url
})
```
I try `getImageUrl` to gallery No 1434389, and it return wrong url.
I also try to connect url with Referer header, it same.
So i think Hitomi uses different image routing rules according to the presence of avif.

**Comment by H2Owater425** [comment]
Thank you for creating an issue to inform me a bug!
I found some mistakes in your source code, but I'll assume that you used `hitomi.getGallery`'s result named `image` as `Gallery['files'][number]`
Nevertheless, I noticed some structural changes in Hitomi's image system that didn't affect just limited galleries
And this time, I guarantee you that you will soon find the new version of this package (not like before)
Again, thanks for your contribution!

이슈 생성을 통해 버그를 보고해주셔서 감사합니다.
주신 코드에서 조금의 실수를 발견했지만 `hitomi.getGallery`의 결과인 `image`로 망명되는 인수를 `hitomi.Gallery['files'][number]`로써 사용하셨으리라 추정하겠습니다
그럼에도 불구하고, 한정된 겔러리에만 작용하는 것이 아닌 히토미 이미지 시스템의 구조적인 변화를 확인했습니다
그리고 이번에는 금방 새로운 버전을 내놓을 것을 장담드립니다 (이전과는 다르게 말이죠)
다시한번, 기여에 감사드립니다!

**Comment by H2Owater425** [comment]
I just released a new release, please check it out for [the package's new version](https://www.npmjs.com/package/node-hitomi)!

**Comment by bass9030** [comment]
I try new version, but `hitomi.getImageUrl` is work with only `isThumbnail: true` option.
Option `isThumbnail: false` returns a page that still does not exist.

새 버전을 시도해봤지만 `isThumbnail`이 true일때만 작동합니다.
`isThumbnail`가 false일때는 여전히 존재하지 않는 링크를 줍니다.

**Comment by H2Owater425** [comment]
This requires some explanation
Before like a month ago, they used a kind of static method to get the url of the image
But after the change, they made an external element that can alter the url of the image so that they can block the outsiders' usage
One good thing is I'm finding a method to fix this problem by making `hitomi.getImageUrl` flexible (#36)
Anyway, as a temporary measure, I'll release a new version of this package

이건 설명이 좀 필요한데요
한 한 달 쯤 전에는 사진 링크를 얻는데 고정된 방법이 사용됐습니다
근데 언젠가부터 외부인의 사용을 막기 위해서인지 외부 요소가 사진 링크를 변경할 수 있게 바꿔놨더라고요
하나 희소식은 제가 `hitomi.getImageUrl`을 변화에 유연하게 반응할 수 있도록 바꾸는 방법을 찾고 있다는겁니다
아무튼 임시방편으로 새 버전을 출시하겠습니다

**Comment by bass9030** [comment]
Oh okay. i will wait it
아 그렇군요 알겠습니다!

**Comment by H2Owater425** [comment]
[The new version](https://www.npmjs.com/package/node-hitomi) has came out, please check it out!
I'll show you some example code for new version down below in javascript.
```javascript
const hitomi = require('node-hitomi').default;

(async function () {
	const imageUrlResolver = new hitomi.ImageUrlResolver();

	await imageUrlResolver.synchronize();

	console.log(imageUrlResolver.getImageUrl(await hitomi.getGallery(/* any number */), 'webp'));
})();
```

[새로운 버전](https://www.npmjs.com/package/node-hitomi)이 출시했습니다, 확인해주세요!
아래에 자바스크립트로 새로운 버전을 위한 예시 코드를 보여드리겠습니다 (상단에 위치)

**Comment by ayenz** [comment]
Hello, I'm still getting "some" wrong image url (404) even I already updated node-hitomi package to latest version (7.0.1)

My Code
```js
const hitomi = require('node-hitomi').default;

(async function () {
    const imageUrlResolver = new hitomi.ImageUrlResolver();
    await imageUrlResolver.synchronize();
    const files = (await hitomi.getGallery(2163268)).files;

    files.forEach(file =>{
        console.log(imageUrlResolver.getImageUrl(file, 'webp'));
    })
})();
```
I got right image for first url, but 404 for second url and so on (random).
I already tried webp or avif but still no luck. Any help is appreciated. Thank you.

**Comment by H2Owater425** [comment]
> Hello, I'm still getting "some" wrong image url (404) even I already updated node-hitomi package to latest version (7.0.1)
> 
> My Code
> ```js
> const hitomi = require('node-hitomi').default;
> 
> (async function () {
>     const imageUrlResolver = new hitomi.ImageUrlResolver();
>     await imageUrlResolver.synchronize();
>     const files = (await hitomi.getGallery(2163268)).files;
> 
>     files.forEach(file =>{
>         console.log(imageUrlResolver.getImageUrl(file, 'webp'));
>     })
> })();
> ```
> I got right image for first url, but 404 for second url and so on (random).
> I already tried webp or avif but still no luck. Any help is appreciated. Thank you. 

First of all, thank you for reporting the issue!
I'll soon start to examine for that problem, please wait until I find whats wrong.

**Comment by ayenz** [comment]
Thank you for your hard work!
I already tested the latest version and now work like a charm.
I'll report if any weird bugs happen. Thank you so much!

**Comment by ayenz** [comment]
And it's not working again. It's a cat and mouse game omg. 
I got 404 for all image urls (avif or webp) using same code for testing latest version (7.0.2).
Sorry for taking your time.

**Comment by H2Owater425** [comment]
Let me check the irregular, once more.
Give me some time, and I'll release a new version.

**Comment by ayenz** [comment]
Don't worry, just take your time. Looking forward for new version! Cheers!

**Comment by H2Owater425** [comment]
@ayenz 
Okay, I just released [the new version](https://www.npmjs.com/package/node-hitomi).
Just in case you're curious, the reason why the package didn't work was Hitomi's creation of another external element that can alter the url of the image.
As always, thank you for using and contributing to the package!

**Comment by ayenz** [comment]
Updated to latest version, now it's working.
It's hard to maintain code for hitomi, even tachiyomi extension for hitomi was already dead.
Thank you for your hard work and make this happen!
