### ISSUE TITLE
HitomiError [REQEUST_REJECTED]: Request to 'https://ltn.hitomi.la/gg.js' was rejected

### ISSUE THREAD

**Issue by dnm13** [H2Owater425/node-hitomi#51]
## Description of bug
Error was thrown, although I quite don't know which function caused this.
Using proper catch didn't worked.

## Expected behavior
The error can be catch on `.catch`
And, should be obvious, but this error should never be thrown, whatever the cause is.

## Environment
- OS: Windows 10
- Version
  - NodeJS: 16.17.0
  - Package: 7.0.5

## Additional context
Error:
```
HitomiError [REQEUST_REJECTED]: Request to 'https://ltn.hitomi.la/gg.js' was rejected
    at ClientRequest.<anonymous> (<omitted>\node_modules\node-hitomi\library\index.js:1:2451)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'REQEUST_REJECTED'
}
```

Code (although I'm not sure which function caused this, these are two functions that I've used with):
```TypeScript
// ...
var getImageUrl = new hitomi.ImageUrlResolver();
// ...

const downloadHitomi: DownloadMethod = function downloadHitomi(file, path) {
    return new Promise<string>(async (resolve, reject) => {
        try {
            const URL = <string>await getImageUrl(<hitomiType.Image>file.hitomiImage, 'webp', {}).catch(err => { return reject(err) });
            // ...
        }
        catch (err) { reject(err) }
    })
};

const getHitomi: GetMethod = function getHitomi(url) {
    return new Promise(async (resolve, reject) => {
        // ...
        const metadata: hitomiType.Gallery = await hitomi.getGallery(parseInt(id!), { includeFiles: true }).catch(err => { return reject(err) });
        // ...
    })
}
```

**Comment by H2Owater425** [comment]
Hmm... I couldn't find any problems with tests on various node versions.
Have you checked your internet connection?

**Comment by dnm13** [comment]
which function made a request for `https://ltn.hitomi.la/gg.js` ?
I'd like to try something with try-catch, can you tell me which one?

**Comment by H2Owater425** [comment]
Since the data of that page is related to generating the image url, `synchronize` method of `ImageUrlResolver` instance makes a request.
Additionally, I want you to check if you can access that page manually with your browser or something.
Sorry that I couldn't be of any help, I hope you find out the problem.

**Comment by dnm13** [comment]
`.catch` didnt work. The error bleeds to the process.

```typescript
const getImageUrl = async function getImageUrl(image: hitomiType.Image, extension: "avif" | "webp", options: { isThumbnail?: boolean | undefined; isSmall?: boolean | undefined; }) {
    if (!IUR) {
        const hitomi: typeof hitomiType = require("node-hitomi").default;
        IUR = new hitomi.ImageUrlResolver();
        await IUR.synchronize().catch((err: Error) => {
            console.log("Error catch from synchronize");
            console.log(err.message);

        }); // first synchronize
    }
    return await IUR.getImageUrl(image, extension, options);
}

// ...

CPM.registerJob("hitomi:startup", () => {
    setInterval(() => {
        if (IUR) IUR.synchronize().catch(
            (err: Error) => {
                console.log("Error catch from synchronize");
                console.log(err.message);
            });
    }, SynchronizeInterval);
});
```

console:
```
HitomiError [REQEUST_REJECTED]: Request to 'https://ltn.hitomi.la/gg.js' was rejected
    at ClientRequest.<anonymous> (<omitted>\node_modules\node-hitomi\library\index.js:1:2451)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'REQEUST_REJECTED'
}
```

To be clear, I'm able to access hitomi.la without any problem, and my app was able to fetch some image before the error was thrown.

```
CPH: Assigning "hitomi:download" job to child process #2
TOKYO NECRO SUICIDE MISSION R downloaded 0
CPH: Assigning "hitomi:download" job to child process #3
TOKYO NECRO SUICIDE MISSION R downloaded 1
CPH: Assigning "hitomi:download" job to child process #4
TOKYO NECRO SUICIDE MISSION R downloaded 2
CPH: Assigning "hitomi:download" job to child process #5
TOKYO NECRO SUICIDE MISSION R downloaded 3
CPH: Assigning "hitomi:download" job to child process #6
```

I was also able to access `https://ltn.hitomi.la/gg.js` on my browser.

I'll try with `try-catch` statement for now, hopefully the error doesn't bleed to the process.

**Comment by dnm13** [comment]
I believe the most important thing to fix here is the fact that the error can't be catch on botch `.catch` and `try-catch` statement.

**Comment by dnm13** [comment]
I suggest to add `.catch()` here:
![image](https://user-images.githubusercontent.com/56634278/213611213-644f9c3d-a7d1-40bb-b5eb-4804b6544737.png)

Code:
```typescript
IUR.synchronize().catch(err => { console.log("Catched an error from synchronize: ", err); return Promise.reject(err) });
```

Console:
```
Error on downloading 4
HitomiError [REQEUST_REJECTED]: Request to 'https://ltn.hitomi.la/gg.js' was rejected
    at ClientRequest.<anonymous> (<omitted>\node_modules\node-hitomi\library\index.js:2:1747)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Retrying...
CPH: Assigning "hitomi:download" job to child process #7
TOKYO NECRO SUICIDE MISSION R downloaded 4
```
Notice that after the error was catched, the loop continues and it retries the operation.

**Comment by H2Owater425** [comment]
Okay, I made a handler for the promise and will keep investigating what made things go wrong.
Also, I want you to know that the package will be refactored and more object-oriented with major version up.
Anyway, I published new release, please check [the package's new version](https://www.npmjs.com/package/node-hitomi).

**Comment by dnm13** [comment]
Okay, the error now can be catched
Should I leave this issue open? because although the error can now be catched, it doesn't actually solve the main problem

**Comment by H2Owater425** [comment]
Since the request problem wasn't solved, I guess it's fine to keep this issue open.
Just let me investigate this problem's cause.
